### ISSUE TITLE
postcss-media-variables with mqpacker

### ISSUE THREAD

**Issue by what1s1ove** [WolfgangKluge/postcss-media-variables#14]
Hello guys! I have a strange behaviour when I try to use these two packages. Here is my gulp-pipe task for postcss:
```
    .pipe(
      postcss([
        postcssimport(),
        mediavariables(),
        hexalpha(),
        autoprefixer(),
        mqpacker({
          sort: (a, b) => a.localeCompare(b),
        }),
        mediavariables(),
      ])
    )
```
 The code I want to convert:
```
:root {
  --min-width: 200px;
}
@media (min-width: var(--min-width)) {
  body {
    background: red;
  }
}

```
If I use it this way, I get this result. I have "background: red" in the css bundle, but some of the media queries are undefined:
<img width="1018" alt="" src="https://user-images.githubusercontent.com/42296182/83939873-e7b6f580-a7e8-11ea-8869-71a30e4b886e.png">
If I swap mqpacker with the mediavariables task, I get this result(there are no any info about "background: red"): 
<img width="1031" alt="изображение" src="https://user-images.githubusercontent.com/42296182/83939933-6ad84b80-a7e9-11ea-90dc-3fb5658575c2.png">

Could you tell me how I can fix it?

**Comment by WolfgangKluge** [comment]
Hi @What1s1ove,
I've to say sorry, but I'm not actively working on this project anymore. So this behavior might come up due to version incompatibilities with postcss itself and/or mqpacker (which I'm not really aware of). So a PR would be very welcome.

Maybe you can provide a much simpler version of your test (your output does not really fit to the provided input). The simplest examples are the most expressive ones. What is the output without postcss-media-variables (and fixed media queries) in such a simplified example? Can you track it down to the two projects (without autoprefixr and hexalpha).
